# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import numpy as np

**1) Crear un arreglo de ceros de longitud 12**

In [ ]:
array = np.zeros(12)
print(array)
array.size

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

**2) Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5**

In [ ]:
array2 = np.zeros(10)
array2[4]  = 10
print(array2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


**3) Crear un arreglo que tenga los números del 10 al 49**

In [ ]:
array3 = np.arange(10,50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**4) Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8**

In [3]:
array4 = np.arange(9).reshape(3,3)
print(array4)
type(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


numpy.ndarray

**5) Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza**

In [4]:
array5 = np.random.rand(100)
print(array5)
print("Media: ",array5.mean())
print("Varianza: ",array5.var())

[0.81726014 0.36166393 0.28255055 0.16586606 0.53634923 0.26659549
 0.94794895 0.97490471 0.95541493 0.71723087 0.49721489 0.28315899
 0.73407204 0.40103686 0.40441483 0.11376436 0.23314216 0.07903098
 0.68965177 0.52319407 0.44876547 0.59270567 0.93075447 0.49864883
 0.69438737 0.81593699 0.1738255  0.66725334 0.95444991 0.75322171
 0.29576928 0.66141176 0.57997297 0.698324   0.20434317 0.53062774
 0.7162093  0.37124475 0.52738112 0.7351109  0.61054491 0.65923717
 0.40609113 0.48267926 0.39636474 0.96534291 0.79805845 0.09601637
 0.36995338 0.44247102 0.2835697  0.72270087 0.08380077 0.08251902
 0.89313653 0.9979145  0.12038659 0.37589141 0.83370618 0.79940862
 0.42907177 0.24672701 0.02494707 0.02257383 0.91786509 0.81538839
 0.95335208 0.98558624 0.15324779 0.05916477 0.75192597 0.22742237
 0.07175217 0.50808391 0.97256051 0.1340413  0.21020723 0.15377508
 0.31926621 0.29084352 0.71938843 0.30097559 0.15681261 0.14057375
 0.08775751 0.4188404  0.11635861 0.23009496 0.73683924 0.1009

**6) Calcular la media de un arreglo usando np.sum**

In [5]:
print("Media: ", array5.sum()/array5.size)

Media:  0.49121977228638686


**7) Calcular la varianza de un arreglo usando np.sum y np.mean**

In [7]:
media = array5.mean()
# Suma de diferencias cuadradas de cada dato respecto a la media
varianza = sum ([(i - media) ** 2 for i in array5]) / (array5.size)
print("Varianza: ",varianza)

Varianza:  0.08576872911662928


**8) Crear un array de números aleatorios usando np.random.randn.**

In [8]:
array6 = np.random.randn(10)
print(array6)

[ 1.29564234  0.56073982  0.72193776  2.30845525  0.96306944 -0.60629859
  0.18688058 -0.09750336  1.89383359 -0.18995247]


# **Notas:**

Difencia entre rand y randn

*  rand genera números con una distribución uniforme, todos los valores tienen la misma probabilidad de ocurrir. Rango específico [0, 1).
*  randn genera números con una distribución normal estándar, centrada en cero con una dispersión (varianza) de uno.